### PR TITLE
Added leaked certificates from Slovenia

### PR DESCRIPTION
**Pull request by stefanb**
Both are **_still_** published on Twitter:
- https://twitter.com/vladaRS/status/1408058639496011780
- https://twitter.com/skledar_tv/status/1458161288236969993

### CODE REVIEW

**Comment by denysvitali** [comment]
Can you please also archive the page (if it's not done yet) on archive.is?

I'll merge the PR later as it still needs a couple of quick fixes (QR code feneration with qrencode), but I'll take care of it.

Thanks!

**Comment by stefanb** [comment]
They are both archived at
- https://archive.md/DmbCK
- https://archive.md/ESN8r

**Comment by stefanb** [comment]
I re-rendered them with `qrencode` as all existing ones in fbe81f7.

**Comment by denysvitali** [comment]
Awesome, thanks!

**Pull request merged**
